module.exports = {
  source: 'dist',
  destination: 'dist',
  include: [
    '/',
    '/getting-started',
    '/blog',
    '/blog/:slug',
    '/learning-paths',
    '/learning-paths/:pathId',
    '/platform-guides',
    '/platform-guides/:slug',
    '/tools/all',
    '/tools/calculator',
    '/tools/niche-quiz',
    '/tools/seo-audit',
    '/tools/keyword-research',
    '/tools/backlink-checker',
    '/tools/performance',
    '/tools/script-generator',
    '/tools/trend-scanner',
    '/tools/channel-analyzer',
    '/news',
    '/resources/templates',
    '/resources/niches',
    '/products/all',
    '/product/:slug',
    '/learning/case-studies',
    '/learning/case-studies/:slug',
    '/learning/workshops',
    '/learning/resources',
    '/privacy-policy',
    '/terms-of-service',
    '/about',
    '/contact',
    '/creator-roadmap',
    '/opportunity-finder',
    '/monetization-matcher',
    '/start-here',
  ],
  minifyHtml: {
    collapseWhitespace: false,
    removeComments: false,
  },
  puppeteerArgs: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-accelerated-2d-canvas',
    '--no-first-run',
    '--no-zygote',
    '--disable-gpu'
  ],
  skipThirdPartyRequests: true,
  cacheAjaxRequests: false,
  removeScriptTags: false,
  removeStyleTags: false,
  // Wait for React to hydrate and content to load
  waitFor: 2000,
  // Crawl from these pages
  crawlFrom: '/',
  // Fix external links
  fixWebpackChunksIssue: false,
  // Headless browser options
  headless: true,
  // Timeout for page load
  timeout: 30000,
};

