import type { FallbackNicheFull } from "./fallbackTypes";

const id = (slug: string) => `fallback-${slug}`;

/** Twenty-one flagship faceless niches (user-requested set) with full detail records. */
export const FALLBACK_CORE_NICHES: FallbackNicheFull[] = [
  {
    slug: "personal-finance-tips-faceless",
    nicheName: "Personal Finance Tips (Animated Explainers)",
    categoryName: "Finance & Wealth",
    description:
      "Animated budgeting breakdowns, saving hacks, and debt payoff stories using infographics, charts, and AI narration—no face required.",
    profitabilityScore: 9,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$4K–$18K/mo (multi-revenue)",
    avgRpm: 18,
    startupCost: "$80–$400 (motion templates + voice + editing)",
    timeToMonetization: "3–6 months (ads + affiliates)",
    evergreenScore: 9,
    trendStatus: "stable",
    targetAudience: "Young professionals and families seeking simple money systems.",
    primaryContentFocus: "Budget frameworks, emergency funds, debt snowball vs avalanche, savings rate tips.",
    monetizationStrategies: [
      "YouTube Partner Program + Shorts",
      "Affiliate tools (banks, budgeting apps)",
      "Notion/Google Sheet budget templates",
      "Newsletter with sponsor slots",
    ],
    risks: [
      "Finance claims require careful disclaimers (not financial advice).",
      "High competition—differentiate with niche geography or income band.",
      "Thumbnail/title policy scrutiny on certain platforms.",
    ],
    requiredTools: ["CapCut or DaVinci Resolve", "Canva or Figma", "AI voice (ElevenLabs-style)", "Chart/data viz"],
    bestAiTools: ["Script assistants", "Voice synthesis", "Auto-captions"],
    longFormContent: `Personal finance remains one of the strongest faceless lanes because search intent is explicit: people type exact problems like “how to stop overspending” or “debt payoff plan.” Animated explainers translate numbers into stories—charts rising and falling, piggy banks, simple characters—so viewers grasp concepts without a talking head. The winning pattern is **one problem per video**, a clear worksheet or rule of thumb, and a single CTA (free spreadsheet, affiliate tool you genuinely use). Rotate evergreen pillars (budgeting, credit, investing basics) with seasonal hooks (tax season, New Year reset). Sustainability comes from updating older videos when tax rules or interest environments shift—your library compounds instead of decaying.`,
    contentIdeas: [
      { contentTitle: "50/30/20 Rule Explained in 60 Seconds", contentFormat: "Shorts / Reels", seoPotential: "High", estimatedProductionTime: "2–4 hrs", requiredTools: ["Motion template", "VO"] },
      { contentTitle: "Debt Snowball vs Avalanche (Animated Case Study)", contentFormat: "Long-form", seoPotential: "Very high", estimatedProductionTime: "8–14 hrs", requiredTools: ["Charts", "Spreadsheet mockups"] },
      { contentTitle: "Emergency Fund: How Much Is Enough?", contentFormat: "Long-form", seoPotential: "High", estimatedProductionTime: "6–10 hrs", requiredTools: ["Infographic scenes"] },
      { contentTitle: "5 Money Mistakes Keeping You Broke", contentFormat: "Shorts series", seoPotential: "Medium", estimatedProductionTime: "1–2 hrs each", requiredTools: ["Text-on-screen"] },
      { contentTitle: "Monthly Budget Walkthrough (Screen + VO)", contentFormat: "Tutorial", seoPotential: "High", estimatedProductionTime: "5–8 hrs", requiredTools: ["Screen capture"] },
    ],
    caseStudies: [
      {
        channelName: "Composite: Animated Finance Explainers",
        contentStyle: "Infographic + VO",
        estimatedEarnings: 9200,
        monthlyViews: 1_200_000,
        subscribersCount: 210_000,
        keySuccessFactors: ["Search-led titles", "Template thumbnails", "Playlist clustering"],
        toolsUsed: ["After Effects templates", "ElevenLabs", "TubeBuddy"],
      },
    ],
  },
  {
    slug: "credit-card-reviews-faceless",
    nicheName: "Credit Card Reviews & Comparisons",
    categoryName: "Finance & Wealth",
    description:
      "Side-by-side reward comparisons, fee breakdowns, and perk maps with charts and calm narration—ideal for affiliate-driven RPM.",
    profitabilityScore: 9,
    difficultyLevel: "hard",
    competitionLevel: "high",
    estimatedEarningsRange: "$6K–$25K/mo (affiliate-heavy)",
    avgRpm: 22,
    startupCost: "$150–$600 (research + design + compliance templates)",
    timeToMonetization: "4–8 months",
    evergreenScore: 7,
    trendStatus: "stable",
    targetAudience: "Travelers, cashback optimizers, and first-card seekers.",
    primaryContentFocus: "Issuer comparisons, APR education, signup strategy, perk utilization.",
    monetizationStrategies: ["Credit card affiliate programs", "Sponsorships (disclosed)", "Premium comparison spreadsheets", "Email list with seasonal offers"],
    risks: ["Strict disclosure and compliance", "Policy changes by issuers", "Audience trust requires accuracy"],
    requiredTools: ["Spec spreadsheets", "Screen capture for issuer sites", "Chart builder"],
    bestAiTools: ["Research summarization (verify manually)", "Script editing"],
    longFormContent: `Credit content monetizes through **high-intent affiliate clicks** when viewers compare specific products. Faceless creators win with **clarity tables**: annual fees, reward categories, foreign transaction fees, and realistic break-even math. Avoid hype; lean into scenarios (“If you spend $X on groceries…”). Update quarterly as offers change. Pair long reviews with Shorts that isolate one perk—airport lounge access, category multipliers—to feed discovery.`,
    contentIdeas: [
      { contentTitle: "Best No-Annual-Fee Cards This Quarter", contentFormat: "Long-form", seoPotential: "Very high", estimatedProductionTime: "10–16 hrs", requiredTools: ["Comparison table"] },
      { contentTitle: "Travel vs Cashback: Which Fits You?", contentFormat: "Animated explainer", seoPotential: "High", estimatedProductionTime: "8–12 hrs", requiredTools: ["Motion graphics"] },
      { contentTitle: "Signup Bonus Math: Don’t Get Trapped", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "2–3 hrs", requiredTools: ["VO"] },
    ],
    caseStudies: [
      { channelName: "Composite: Card Comparison Channel", contentStyle: "Charts + VO", estimatedEarnings: 14000, monthlyViews: 900_000, subscribersCount: 160_000, keySuccessFactors: ["Tables in thumbnails", "Monthly refresh cadence"], toolsUsed: ["Notion research DB", "Figma"] },
    ],
  },
  {
    slug: "investing-for-beginners-faceless",
    nicheName: "Investing for Beginners (Stocks, ETFs, Macro Updates)",
    categoryName: "Finance & Wealth",
    description:
      "Market explainers, ETF guides, and portfolio basics via screen shares, charts, and neutral narration—faceless and compliance-aware.",
    profitabilityScore: 9,
    difficultyLevel: "hard",
    competitionLevel: "high",
    estimatedEarningsRange: "$5K–$22K/mo",
    avgRpm: 20,
    startupCost: "$100–$500",
    timeToMonetization: "4–9 months",
    evergreenScore: 8,
    trendStatus: "rising",
    targetAudience: "First-time investors avoiding jargon walls.",
    primaryContentFocus: "ETFs, diversification, risk, simple macro context (non-advice).",
    monetizationStrategies: ["Ads", "Affiliate brokers (where allowed)", "Courses/templates", "Newsletter"],
    risks: ["Never guarantee returns", "Regulatory sensitivity—use disclaimers", "Volatile comment sections"],
    requiredTools: ["TradingView or charting", "Screen recorder", "Fact-check workflow"],
    bestAiTools: ["Script structuring", "Captioning"],
    longFormContent: `Beginner investing faceless channels succeed when they **teach mechanics**, not hot picks. Use screen recordings to walk brokerage UIs, demonstrate limit orders vs market orders, and compare ETFs by expense ratio. Macro “news update” shorts can spike views; anchor them to education so the channel stays evergreen. Sustainability means citing sources, avoiding day-trading hype, and maintaining a calm tone that survives market drawdowns without audience churn.`,
    contentIdeas: [
      { contentTitle: "ETFs Explained Like You're Five", contentFormat: "Animation", seoPotential: "Very high", estimatedProductionTime: "10–20 hrs", requiredTools: ["Motion"] },
      { contentTitle: "3-Fund Portfolio Walkthrough", contentFormat: "Screen tutorial", seoPotential: "High", estimatedProductionTime: "6–10 hrs", requiredTools: ["OBS"] },
      { contentTitle: "Market News Without the Panic", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "2–4 hrs", requiredTools: ["News screenshots"] },
    ],
    caseStudies: [
      { channelName: "Composite: ETF Education", contentStyle: "Screen + charts", estimatedEarnings: 11000, monthlyViews: 1_100_000, subscribersCount: 240_000, keySuccessFactors: ["Neutral tone", "Chapters", "Glossary pinned comment"], toolsUsed: ["TradingView", "Descript"] },
    ],
  },
  {
    slug: "guided-meditations-faceless",
    nicheName: "Guided Meditations & Sleep Audio",
    categoryName: "Health & Wellness",
    description:
      "Calming visuals, ambient beds, and AI or soft-spoken narration for sleep, anxiety, and focus—100% faceless.",
    profitabilityScore: 7,
    difficultyLevel: "easy",
    competitionLevel: "medium",
    estimatedEarningsRange: "$2K–$12K/mo",
    avgRpm: 8,
    startupCost: "$50–$300",
    timeToMonetization: "2–5 months",
    evergreenScore: 10,
    trendStatus: "stable",
    targetAudience: "Stressed workers, students, insomnia sufferers.",
    primaryContentFocus: "Breath cues, body scans, sleep stories, nature soundscapes.",
    monetizationStrategies: ["Ads", "Memberships", "Spotify/Apple Music distribution (where applicable)", "Calm-style digital bundles"],
    risks: ["Copyright on music—use licensed assets", "Repetitive content—rotate themes"],
    requiredTools: ["DAW (Reaper/Audacity)", "Royalty-free music", "Looping visuals"],
    bestAiTools: ["Voice softening", "Script pacing"],
    longFormContent: `Meditation content monetizes through **volume + session time**. Long uploads (1–8 hours) can rank in search for “rain sleep” or “guided anxiety relief.” Faceless visuals—slow nature loops, abstract gradients—keep production scalable. Differentiate with niche scripts: exam anxiety, pre-interview calm, grief-aware language. Avoid medical claims; position as relaxation entertainment.`,
    contentIdeas: [
      { contentTitle: "10-Minute Anxiety Grounding", contentFormat: "Long audio + loop", seoPotential: "High", estimatedProductionTime: "4–8 hrs", requiredTools: ["DAW"] },
      { contentTitle: "Deep Sleep Story (Rain)", contentFormat: "8hr loop", seoPotential: "Very high", estimatedProductionTime: "6–12 hrs (asset prep)", requiredTools: ["Visual loop"] },
      { contentTitle: "Focus Music + Light Cues", contentFormat: "Shorts teaser → long", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["VO"] },
    ],
    caseStudies: [
      { channelName: "Composite: Sleep Audio Brand", contentStyle: "Loops + VO", estimatedEarnings: 4800, monthlyViews: 3_500_000, subscribersCount: 420_000, keySuccessFactors: ["Long uploads", "Consistent thumbnails"], toolsUsed: ["Epidemic Sound", "Premiere"] },
    ],
  },
  {
    slug: "fitness-routines-faceless",
    nicheName: "Fitness Routines & Home Workouts",
    categoryName: "Health & Wellness",
    description:
      "Demonstrations via stock clips, kinetic text timers, and voice coaching—no face cam needed.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$3K–$15K/mo",
    avgRpm: 11,
    startupCost: "$100–$400",
    timeToMonetization: "3–7 months",
    evergreenScore: 8,
    trendStatus: "stable",
    targetAudience: "Home trainees, busy parents, minimal-equipment users.",
    primaryContentFocus: "HIIT, mobility, posture fixes, progressive overload basics.",
    monetizationStrategies: ["Ads", "Affiliate equipment", "PDF programs", "App referrals"],
    risks: ["Injury disclaimers", "Form criticism—use clear cues", "Stock clip licensing"],
    requiredTools: ["Licensed stock or AI-generated B-roll (policy-compliant)", "Timer overlays", "Music"],
    bestAiTools: ["Script for cues", "Auto-captions"],
    longFormContent: `Faceless fitness works when **timing and clarity** replace personality. Build series: “20-minute dumbbell week,” “Desk neck fix.” Use countdown overlays and rep counters. Monetize with programs once a series proves retention. Film-free creators often partner with athletes for short licensed clips or use animation silhouettes.`,
    contentIdeas: [
      { contentTitle: "20-Min Full Body (No Equipment)", contentFormat: "Follow-along", seoPotential: "High", estimatedProductionTime: "8–14 hrs", requiredTools: ["Timer template"] },
      { contentTitle: "Fix Anterior Pelvic Tilt (3 Drills)", contentFormat: "Explainer", seoPotential: "High", estimatedProductionTime: "6–10 hrs", requiredTools: ["Diagrams"] },
      { contentTitle: "Tabata Timer: Belly Fat Myths", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "2–4 hrs", requiredTools: ["Text hooks"] },
    ],
    caseStudies: [
      { channelName: "Composite: Timer-Style Workouts", contentStyle: "Overlays + VO", estimatedEarnings: 7200, monthlyViews: 1_800_000, subscribersCount: 310_000, keySuccessFactors: ["Series playlists", "Clear difficulty labels"], toolsUsed: ["CapCut timers", "Artlist"] },
    ],
  },
  {
    slug: "nutrition-advice-faceless",
    nicheName: "Nutrition Advice & Meal Prep Visuals",
    categoryName: "Health & Wellness",
    description:
      "Overhead meal prep, macro explainers, and plate-method tutorials using footage + text—no on-camera host.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$3K–$14K/mo",
    avgRpm: 12,
    startupCost: "$80–$350",
    timeToMonetization: "3–6 months",
    evergreenScore: 8,
    trendStatus: "stable",
    targetAudience: "Busy professionals, fat-loss beginners, meal planners.",
    primaryContentFocus: "Meal prep, high-protein ideas, simple grocery lists, myth busting (non-medical).",
    monetizationStrategies: ["Ads", "Affiliate kitchen gear", "Meal plan PDFs", "Sponsored pantry brands"],
    risks: ["Avoid medical nutrition therapy claims", "Allergy sensitivity in recipes"],
    requiredTools: ["Overhead rig or stock", "Macro graphics", "Recipe cards"],
    bestAiTools: ["Recipe copy editing", "Thumbnail text"],
    longFormContent: `Nutrition faceless channels win with **visual recipes + education**. Macro explainers with plates and labels outperform vague motivation. Use “if it fits your calories” frameworks rather than shame. Affiliate kitchen tools and grocery apps convert when demonstrated in-context.`,
    contentIdeas: [
      { contentTitle: "High-Protein Meal Prep (5 Meals)", contentFormat: "Top-down", seoPotential: "High", estimatedProductionTime: "10–18 hrs", requiredTools: ["Kitchen footage"] },
      { contentTitle: "Sugar Cravings: Habit Loop Explainer", contentFormat: "Animation", seoPotential: "Medium", estimatedProductionTime: "8–12 hrs", requiredTools: ["Motion"] },
      { contentTitle: "Grocery List for $50 Week", contentFormat: "Shorts series", seoPotential: "High", estimatedProductionTime: "4–6 hrs", requiredTools: ["VO"] },
    ],
    caseStudies: [
      { channelName: "Composite: Macro Meal Channel", contentStyle: "Overhead + VO", estimatedEarnings: 6500, monthlyViews: 950_000, subscribersCount: 175_000, keySuccessFactors: ["Consistent lighting", "Printable lists"], toolsUsed: ["Canva", "Notion"] },
    ],
  },
  {
    slug: "software-tutorials-faceless",
    nicheName: "Software Tutorials (Notion, Excel, Canva)",
    categoryName: "Tech & Productivity",
    description:
      "Screen-first teaching: workflows, formulas, and templates with crisp narration—classic faceless education.",
    profitabilityScore: 9,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$5K–$20K/mo",
    avgRpm: 16,
    startupCost: "$60–$300",
    timeToMonetization: "2–5 months",
    evergreenScore: 9,
    trendStatus: "rising",
    targetAudience: "Students, operators, creators automating work.",
    primaryContentFocus: "Click-by-click workflows, template sales, integration tips.",
    monetizationStrategies: ["Ads", "Template marketplace", "Affiliate SaaS", "Skool/community (optional)"],
    risks: ["UI changes break videos—plan updates", "Trademark respect in thumbnails"],
    requiredTools: ["OBS", "Mic or clean AI voice", "Zoom cursor highlights"],
    bestAiTools: ["Step generator from changelog", "Captioning"],
    longFormContent: `Software tutorials are the **purest faceless format**: the screen is the star. Win with tight scripts, slow cursor movement on critical steps, and downloadable files. Build template businesses once a workflow repeats in comments.`,
    contentIdeas: [
      { contentTitle: "Notion CRM in 15 Minutes", contentFormat: "Screen tutorial", seoPotential: "Very high", estimatedProductionTime: "6–12 hrs", requiredTools: ["OBS"] },
      { contentTitle: "Excel INDEX/MATCH for Beginners", contentFormat: "Long-form", seoPotential: "Very high", estimatedProductionTime: "8–14 hrs", requiredTools: ["Spreadsheet"] },
      { contentTitle: "Canva Bulk Create Shorts", contentFormat: "Tutorial", seoPotential: "High", estimatedProductionTime: "5–9 hrs", requiredTools: ["Canva"] },
    ],
    caseStudies: [
      { channelName: "Composite: Notion Systems", contentStyle: "Screen + VO", estimatedEarnings: 13000, monthlyViews: 800_000, subscribersCount: 140_000, keySuccessFactors: ["Free template gate", "Update notes in description"], toolsUsed: ["Notion", "Loom"] },
    ],
  },
  {
    slug: "gadget-reviews-faceless",
    nicheName: "Gadget Reviews (Hands-Only & Spec Tables)",
    categoryName: "Tech & Productivity",
    description:
      "Unboxings with gloved or desk-only hands, spec comparisons, and affiliate overlays—identity stays private.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$4K–$18K/mo",
    avgRpm: 14,
    startupCost: "$200–$800 (gear samples or rentals)",
    timeToMonetization: "3–6 months",
    evergreenScore: 6,
    trendStatus: "rising",
    targetAudience: "Tech shoppers comparing phones, earbuds, and desk gear.",
    primaryContentFocus: "Benchmark tables, mic tests, battery loops, honest cons lists.",
    monetizationStrategies: ["Affiliate retail links", "Sponsorships", "Shorts discovery → long reviews"],
    risks: ["Return policies for loaner units", "Bias perception—publish methodology"],
    requiredTools: ["B-roll camera", "Audio test rig", "Lighting box"],
    bestAiTools: ["Spec summarization (verify)", "Thumbnail copy"],
    longFormContent: `Hands-only reviews keep personality minimal while preserving **trust signals**: standardized mic tests, brightness sweeps, and heat maps. Shorts tease one test; long videos compile the verdict.`,
    contentIdeas: [
      { contentTitle: "Earbuds Mic Test (Street Noise)", contentFormat: "B-roll", seoPotential: "Medium", estimatedProductionTime: "8–14 hrs", requiredTools: ["Recorder"] },
      { contentTitle: "Best Budget Phones Under $300", contentFormat: "Comparison", seoPotential: "High", estimatedProductionTime: "12–20 hrs", requiredTools: ["Spec sheet"] },
    ],
    caseStudies: [
      { channelName: "Composite: Desk Review Lab", contentStyle: "Hands-only", estimatedEarnings: 9000, monthlyViews: 1_100_000, subscribersCount: 260_000, keySuccessFactors: ["Test methodology pinned"], toolsUsed: ["Decibel meter", "Elgato"] },
    ],
  },
  {
    slug: "coding-basics-faceless",
    nicheName: "Coding Basics & Dev Tutorials",
    categoryName: "Tech & Productivity",
    description:
      "Editor-first teaching: algorithms, web dev, and automation with screen + keystroke captions.",
    profitabilityScore: 9,
    difficultyLevel: "hard",
    competitionLevel: "high",
    estimatedEarningsRange: "$5K–$25K/mo",
    avgRpm: 17,
    startupCost: "$80–$400",
    timeToMonetization: "3–8 months",
    evergreenScore: 9,
    trendStatus: "rising",
    targetAudience: "Career switchers and self-taught devs.",
    primaryContentFocus: "Fundamentals, projects, debugging mindset, tooling.",
    monetizationStrategies: ["Ads", "Bootcamp affiliates", "GitHub sponsor + courses", "Technical newsletter"],
    risks: ["Rapid stack churn—refresh often", "Copy-paste solutions need ethics notes"],
    requiredTools: ["VS Code", "Terminal theming", "Clear font + zoom"],
    bestAiTools: ["Code explanation assistants (review carefully)"],
    longFormContent: `Coding faceless is the default for many educators. Differentiate with **project arcs**—build a SaaS landing page across ten episodes—and with error episodes that normalize debugging.`,
    contentIdeas: [
      { contentTitle: "JavaScript Closures Explained", contentFormat: "Screen lecture", seoPotential: "Very high", estimatedProductionTime: "10–18 hrs", requiredTools: ["Editor"] },
      { contentTitle: "Build a Chrome Extension (Day 1–3)", contentFormat: "Series", seoPotential: "High", estimatedProductionTime: "20–40 hrs total", requiredTools: ["Git"] },
    ],
    caseStudies: [
      { channelName: "Composite: Zero-to-Project JS", contentStyle: "IDE-only", estimatedEarnings: 15000, monthlyViews: 600_000, subscribersCount: 190_000, keySuccessFactors: ["Repo links", "Timestamps"], toolsUsed: ["GitHub", "Obsidian"] },
    ],
  },
  {
    slug: "motivational-stories-faceless",
    nicheName: "Motivational Stories & Parables",
    categoryName: "Lifestyle & Entertainment",
    description:
      "Narrated stories with cinematic stock, quote cards, and chapter-style pacing—emotion without a face.",
    profitabilityScore: 7,
    difficultyLevel: "easy",
    competitionLevel: "medium",
    estimatedEarningsRange: "$2K–$10K/mo",
    avgRpm: 9,
    startupCost: "$50–$250",
    timeToMonetization: "2–5 months",
    evergreenScore: 7,
    trendStatus: "stable",
    targetAudience: "Late-night scrollers seeking reflection and discipline framing.",
    primaryContentFocus: "Stoic lessons, entrepreneur parables, comeback arcs (ethical sourcing).",
    monetizationStrategies: ["Ads", "Membership", "Audiobook-style compilations", "Merch quotes (original)"],
    risks: ["Copyright on clips—use licensed footage", "Avoid plagiarized scripts"],
    requiredTools: ["Stock libraries", "VO chain", "Sound design"],
    bestAiTools: ["Draft outlines—human edit voice"],
    longFormContent: `Story channels scale with **voice + pacing**. Write original scripts or use licensed public-domain literature with commentary. Thumbnails should promise a single emotional payoff.`,
    contentIdeas: [
      { contentTitle: "The Carpenter Who Fixed His Schedule", contentFormat: "Story", seoPotential: "Medium", estimatedProductionTime: "6–10 hrs", requiredTools: ["Stock"] },
      { contentTitle: "3 Habits That Quiet Anxiety", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["Text animation"] },
    ],
    caseStudies: [
      { channelName: "Composite: Parable Voice", contentStyle: "Narration + B-roll", estimatedEarnings: 4100, monthlyViews: 2_100_000, subscribersCount: 380_000, keySuccessFactors: ["Upload consistency", "Hook first line"], toolsUsed: ["Artlist", "Premiere"] },
    ],
  },
  {
    slug: "travel-hacks-faceless",
    nicheName: "Travel Hacks & Budget Itineraries",
    categoryName: "Lifestyle & Entertainment",
    description:
      "Maps, price trackers, packing grids, and destination explainers using stock destination clips.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$3K–$14K/mo",
    avgRpm: 12,
    startupCost: "$80–$400",
    timeToMonetization: "3–7 months",
    evergreenScore: 7,
    trendStatus: "rising",
    targetAudience: "Budget travelers and remote workers planning trips.",
    primaryContentFocus: "Itineraries, mistake avoidance, insurance basics, packing systems.",
    monetizationStrategies: ["Affiliate travel gear", "Ads", "Itinerary PDFs", "Hotel/airline programs (disclosed)"],
    risks: ["Changing visa rules—date your content", "Avoid stereotype thumbnails"],
    requiredTools: ["Map animations", "Stock aerials", "Pricing screenshots"],
    bestAiTools: ["Itinerary drafting—verify live prices"],
    longFormContent: `Travel faceless works when you deliver **checklists and maps** viewers can screenshot. Pair seasonal spikes (summer Europe) with evergreen packing guides.`,
    contentIdeas: [
      { contentTitle: "72 Hours in Lisbon (Budget)", contentFormat: "Itinerary", seoPotential: "High", estimatedProductionTime: "10–16 hrs", requiredTools: ["Maps"] },
      { contentTitle: "Carry-On Only Packing Grid", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["Flatlay stock"] },
    ],
    caseStudies: [
      { channelName: "Composite: Map-First Travel", contentStyle: "Motion maps + VO", estimatedEarnings: 6800, monthlyViews: 720_000, subscribersCount: 150_000, keySuccessFactors: ["Downloadable maps"], toolsUsed: ["Google My Maps"] },
    ],
  },
  {
    slug: "mobile-game-reviews-faceless",
    nicheName: "Mobile Game Reviews & Rankings",
    categoryName: "Lifestyle & Entertainment",
    description:
      "Gameplay capture, tier lists, and patch notes with energetic VO—no face cam needed.",
    profitabilityScore: 7,
    difficultyLevel: "easy",
    competitionLevel: "medium",
    estimatedEarningsRange: "$2K–$12K/mo",
    avgRpm: 7,
    startupCost: "$100–$400",
    timeToMonetization: "2–5 months",
    evergreenScore: 5,
    trendStatus: "rising",
    targetAudience: "Casual gamers hunting underrated titles.",
    primaryContentFocus: "Reviews, hidden gems, monetization critique of F2P models.",
    monetizationStrategies: ["Ads", "Sponsor integrations", "Affiliate peripherals", "Discord memberships"],
    risks: ["Copyright strikes—use permitted capture", "Kids audience brand safety"],
    requiredTools: ["Phone capture + mirroring", "Overlay templates"],
    bestAiTools: ["Patch note summaries"],
    longFormContent: `Mobile gaming channels thrive on **cadence**: new releases weekly, tier lists monthly. Faceless is normal—VO + text reactions carry personality.`,
    contentIdeas: [
      { contentTitle: "Top 10 Offline Games (No Wi-Fi)", contentFormat: "Compilation", seoPotential: "High", estimatedProductionTime: "12–20 hrs", requiredTools: ["Capture"] },
      { contentTitle: "This Update Broke the Meta", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "2–4 hrs", requiredTools: ["Gameplay"] },
    ],
    caseStudies: [
      { channelName: "Composite: Tier List Mobile", contentStyle: "Gameplay + VO", estimatedEarnings: 5200, monthlyViews: 4_200_000, subscribersCount: 510_000, keySuccessFactors: ["Fast uploads on patch days"], toolsUsed: ["CapCut"] },
    ],
  },
  {
    slug: "side-hustle-ideas-faceless",
    nicheName: "Side Hustle Ideas & Micro-Case Studies",
    categoryName: "Business & Marketing",
    description:
      "Visual case studies on freelancing, print-on-demand, and digital products—charts instead of guru faces.",
    profitabilityScore: 9,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$5K–$20K/mo",
    avgRpm: 15,
    startupCost: "$60–$300",
    timeToMonetization: "3–6 months",
    evergreenScore: 8,
    trendStatus: "stable",
    targetAudience: "9–5 employees seeking ethical extra income.",
    primaryContentFocus: "Offer positioning, pricing, time audits, realistic earnings bands.",
    monetizationStrategies: ["Ads", "Course affiliates", "Notion templates", "Newsletter sponsors"],
    risks: ["Income claims—use ranges + disclaimers", "Avoid MLM promotion"],
    requiredTools: ["Chart animations", "Screen captures of dashboards (anonymized)"],
    bestAiTools: ["Outline frameworks"],
    longFormContent: `Side hustle faceless channels succeed with **evidence hygiene**: anonymized dashboards, hours-per-dollar math, and transparent failures.`,
    contentIdeas: [
      { contentTitle: "Freelance Writing: First $1K Month", contentFormat: "Case breakdown", seoPotential: "High", estimatedProductionTime: "8–12 hrs", requiredTools: ["Slides"] },
      { contentTitle: "5 Side Hustles to Skip in 2026", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["VO"] },
    ],
    caseStudies: [
      { channelName: "Composite: Honest Hustle Lab", contentStyle: "Slides + VO", estimatedEarnings: 9800, monthlyViews: 640_000, subscribersCount: 125_000, keySuccessFactors: ["Ranges not guarantees"], toolsUsed: ["Sheets"] },
    ],
  },
  {
    slug: "email-marketing-guides-faceless",
    nicheName: "Email Marketing & Funnel Guides",
    categoryName: "Business & Marketing",
    description:
      "Slide-based breakdowns of sequences, automations, and copy teardowns—screen-led and faceless.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "medium",
    estimatedEarningsRange: "$4K–$16K/mo",
    avgRpm: 14,
    startupCost: "$80–$350",
    timeToMonetization: "3–6 months",
    evergreenScore: 8,
    trendStatus: "stable",
    targetAudience: "Creators and SMBs building lists.",
    primaryContentFocus: "Flows, segmentation, deliverability basics, subject-line tests.",
    monetizationStrategies: ["ESP affiliate trials", "Template packs", "Workshop tickets", "Sponsorships"],
    risks: ["Spam policy education—avoid dark patterns"],
    requiredTools: ["ESP demo account", "Slides", "Loom-style exports"],
    bestAiTools: ["Copy variants (edited)"],
    longFormContent: `Teach email as **systems**: diagrams of triggers, goals per message, and metrics that matter (reply rate, not vanity opens).`,
    contentIdeas: [
      { contentTitle: "Welcome Sequence Map (3 Emails)", contentFormat: "Whiteboard animation", seoPotential: "High", estimatedProductionTime: "8–12 hrs", requiredTools: ["FigJam export"] },
      { contentTitle: "Segmentation in Plain English", contentFormat: "Long-form", seoPotential: "Medium", estimatedProductionTime: "10–14 hrs", requiredTools: ["Slides"] },
    ],
    caseStudies: [
      { channelName: "Composite: Inbox Systems", contentStyle: "Slides + VO", estimatedEarnings: 7600, monthlyViews: 410_000, subscribersCount: 88_000, keySuccessFactors: ["Downloadable flow PDF"], toolsUsed: ["Kit", "Canva"] },
    ],
  },
  {
    slug: "pinterest-strategies-faceless",
    nicheName: "Pinterest Growth & Pin Design",
    categoryName: "Business & Marketing",
    description:
      "Screen captures of Tailwind-style workflows, pin templates, and SEO descriptions—faceless by default.",
    profitabilityScore: 8,
    difficultyLevel: "easy",
    competitionLevel: "medium",
    estimatedEarningsRange: "$3K–$12K/mo",
    avgRpm: 13,
    startupCost: "$50–$200",
    timeToMonetization: "2–5 months",
    evergreenScore: 8,
    trendStatus: "stable",
    targetAudience: "Bloggers, Etsy sellers, and content repurposers.",
    primaryContentFocus: "Pin design systems, keyworded descriptions, board strategy.",
    monetizationStrategies: ["Ads", "Template sales", "Affiliate tools", "Mini-course"],
    risks: ["Platform UI changes", "Overpromising viral timelines"],
    requiredTools: ["Canva", "Pinterest + analytics screenshots"],
    bestAiTools: ["Keyword clustering assistance"],
    longFormContent: `Pinterest education monetizes through **templates**—sell the boards, fonts, and sizing presets you actually use.`,
    contentIdeas: [
      { contentTitle: "Pin Description Formula (Copy-Paste)", contentFormat: "Screen tutorial", seoPotential: "High", estimatedProductionTime: "4–7 hrs", requiredTools: ["Canva"] },
      { contentTitle: "Idea Pins vs Static—When to Use", contentFormat: "Explainer", seoPotential: "Medium", estimatedProductionTime: "6–9 hrs", requiredTools: ["Slides"] },
    ],
    caseStudies: [
      { channelName: "Composite: Pin Systems", contentStyle: "Screen + VO", estimatedEarnings: 5400, monthlyViews: 380_000, subscribersCount: 72_000, keySuccessFactors: ["Template lead magnet"], toolsUsed: ["Canva Pro"] },
    ],
  },
  {
    slug: "book-summaries-faceless",
    nicheName: "Book Summaries & Key Takeaways",
    categoryName: "Evergreen Education",
    description:
      "Chapter-style narration over thematic stock and quote cards—classic faceless learning.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$4K–$16K/mo",
    avgRpm: 12,
    startupCost: "$50–$200",
    timeToMonetization: "3–6 months",
    evergreenScore: 9,
    trendStatus: "stable",
    targetAudience: "Professionals seeking compressed wisdom.",
    primaryContentFocus: "Nonfiction categories: productivity, leadership, psychology.",
    monetizationStrategies: ["Ads", "Audiobook affiliates", "Paid study guides", "Newsletter"],
    risks: ["Copyright—summarize, don’t reproduce", "Fair use education"],
    requiredTools: ["Script citations", "Stock", "Chapter structure"],
    bestAiTools: ["Outline help—human synthesis"],
    longFormContent: `Book summary channels win when they **add commentary**: frameworks, critiques, and action steps—not Wikipedia recaps.`,
    contentIdeas: [
      { contentTitle: "Atomic Habits in 18 Minutes", contentFormat: "Explainer", seoPotential: "Very high", estimatedProductionTime: "10–16 hrs", requiredTools: ["Slides"] },
      { contentTitle: "3 Ideas from Thinking Fast and Slow", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["Text"] },
    ],
    caseStudies: [
      { channelName: "Composite: Framework Summaries", contentStyle: "VO + cards", estimatedEarnings: 8200, monthlyViews: 1_000_000, subscribersCount: 195_000, keySuccessFactors: ["Action steps end card"], toolsUsed: ["Notion research"] },
    ],
  },
  {
    slug: "language-learning-faceless",
    nicheName: "Language Learning Drills & Flashcards",
    categoryName: "Evergreen Education",
    description:
      "Phrase lessons with text cards, native audio loops, and minimal pairs—no instructor face.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "high",
    estimatedEarningsRange: "$3K–$14K/mo",
    avgRpm: 10,
    startupCost: "$80–$350",
    timeToMonetization: "3–7 months",
    evergreenScore: 10,
    trendStatus: "stable",
    targetAudience: "Travelers and polyglot hobbyists.",
    primaryContentFocus: "Pronunciation, spaced repetition, listening loops.",
    monetizationStrategies: ["Ads", "Patreon packs", "Anki deck sales", "Tutoring waitlist"],
    risks: ["Accent accuracy—hire native checks", "Cultural sensitivity"],
    requiredTools: ["Clean typography", "IPA overlays", "Royalty audio"],
    bestAiTools: ["Example sentences—native review"],
    longFormContent: `Language faceless formats shine with **audio-first** Shorts and looping drills. Build level pathways (A1–B1) as playlists.`,
    contentIdeas: [
      { contentTitle: "500 Most Common Verbs (Audio Loop)", contentFormat: "Compilation", seoPotential: "High", estimatedProductionTime: "20–40 hrs", requiredTools: ["DAW"] },
      { contentTitle: "Minimal Pairs: Ship/Sheep", contentFormat: "Shorts", seoPotential: "Medium", estimatedProductionTime: "3–5 hrs", requiredTools: ["Mic"] },
    ],
    caseStudies: [
      { channelName: "Composite: Audio Drill Channel", contentStyle: "Cards + audio", estimatedEarnings: 6100, monthlyViews: 1_300_000, subscribersCount: 290_000, keySuccessFactors: ["Playlist levels"], toolsUsed: ["Anki", "Audacity"] },
    ],
  },
  {
    slug: "diy-home-hacks-faceless",
    nicheName: "DIY Home Hacks & Repairs",
    categoryName: "Evergreen Education",
    description:
      "Step animations and stock clips for fixes, decor, and organization—great for Shorts + Pinterest.",
    profitabilityScore: 8,
    difficultyLevel: "medium",
    competitionLevel: "medium",
    estimatedEarningsRange: "$4K–$15K/mo",
    avgRpm: 11,
    startupCost: "$100–$400",
    timeToMonetization: "3–6 months",
    evergreenScore: 9,
    trendStatus: "stable",
    targetAudience: "Renters, new homeowners, budget upgraders.",
    primaryContentFocus: "Quick repairs, renter-friendly upgrades, storage hacks.",
    monetizationStrategies: ["Ads", "Amazon affiliates", "Sponsored tools", "PDF checklists"],
    risks: ["Safety disclaimers for electrical/plumbing", "Tool misuse liability"],
    requiredTools: ["Overhead shots or stock", "Graphics for warnings"],
    bestAiTools: ["Step ordering checklists"],
    longFormContent: `DIY faceless content must foreground **safety**: gloves, goggles, breaker-off labels. Monetize with tool lists that genuinely match the task.`,
    contentIdeas: [
      { contentTitle: "Fix a Running Toilet (5 Tools)", contentFormat: "Explainer", seoPotential: "Very high", estimatedProductionTime: "8–14 hrs", requiredTools: ["B-roll"] },
      { contentTitle: "Renter-Friendly Shelf Hack", contentFormat: "Shorts", seoPotential: "High", estimatedProductionTime: "4–7 hrs", requiredTools: ["Stock"] },
    ],
    caseStudies: [
      { channelName: "Composite: Fix-It Motion", contentStyle: "Motion steps + VO", estimatedEarnings: 7400, monthlyViews: 890_000, subscribersCount: 175_000, keySuccessFactors: ["Safety callouts"], toolsUsed: ["Artgrid"] },
    ],
  },
  {
    slug: "niche-sports-highlights-faceless",
    nicheName: "Niche Sports Highlights & Tips",
    categoryName: "Niche Hobbies",
    description:
      "Pickleball, climbing, surfing explainers with licensed or original clips and commentary VO.",
    profitabilityScore: 7,
    difficultyLevel: "medium",
    competitionLevel: "medium",
    estimatedEarningsRange: "$2K–$10K/mo",
    avgRpm: 8,
    startupCost: "$150–$600",
    timeToMonetization: "3–7 months",
    evergreenScore: 6,
    trendStatus: "rising",
    targetAudience: "Growing sport communities seeking technique content.",
    primaryContentFocus: "Rules, drills, gear explainers, event recaps (rights-safe).",
    monetizationStrategies: ["Ads", "Affiliate gear", "Club partnerships", "Coaching waitlists"],
    risks: ["Footage rights", "Safety in technique demos"],
    requiredTools: ["Licensed sports footage or original", "Telestrator overlays"],
    bestAiTools: ["Rulebook summaries—verify"],
    longFormContent: `Niche sports reward **early-community** positioning. Be the clearest rules + drills channel before the niche matures.`,
    contentIdeas: [
      { contentTitle: "Pickleball Third Shot Drop (Slow-Mo Explainer)", contentFormat: "Analysis", seoPotential: "Medium", estimatedProductionTime: "10–16 hrs", requiredTools: ["Clips"] },
      { contentTitle: "Beginner Climbing Footwork Drills", contentFormat: "Tutorial", seoPotential: "Medium", estimatedProductionTime: "8–12 hrs", requiredTools: ["Gym B-roll"] },
    ],
    caseStudies: [
      { channelName: "Composite: Niche Sport Lab", contentStyle: "Analysis VO", estimatedEarnings: 4600, monthlyViews: 520_000, subscribersCount: 96_000, keySuccessFactors: ["Weekend upload rhythm"], toolsUsed: ["Hudl"] },
    ],
  },
  {
    slug: "asmr-relaxation-faceless",
    nicheName: "ASMR & Relaxation Soundscapes",
    categoryName: "Niche Hobbies",
    description:
      "Rain, typing, brush sounds with looping visuals—faceless and highly bingeable.",
    profitabilityScore: 7,
    difficultyLevel: "easy",
    competitionLevel: "medium",
    estimatedEarningsRange: "$2K–$11K/mo",
    avgRpm: 7,
    startupCost: "$80–$400",
    timeToMonetization: "2–5 months",
    evergreenScore: 10,
    trendStatus: "stable",
    targetAudience: "Sleep seekers, study cohorts, anxiety relief searchers.",
    primaryContentFocus: "Triggers, layered sound, long sessions.",
    monetizationStrategies: ["Ads", "Memberships", "Tip jars", "Spotify mirrors"],
    risks: ["Ear fatigue content—vary dynamics", "Loudness normalization"],
    requiredTools: ["Binaural mic (optional)", "DAW", "Visual loops"],
    bestAiTools: ["Minimal—sound design is human-first"],
    longFormContent: `ASMR rewards **consistency and audio fidelity**. Publish long sessions; use chapters for triggers.`,
    contentIdeas: [
      { contentTitle: "3 Hours Cozy Rain + Page Turns", contentFormat: "Long loop", seoPotential: "High", estimatedProductionTime: "8–14 hrs", requiredTools: ["DAW"] },
      { contentTitle: "Keyboard ASMR for Studying", contentFormat: "2hr loop", seoPotential: "Medium", estimatedProductionTime: "6–10 hrs", requiredTools: ["Mechanical keys"] },
    ],
    caseStudies: [
      { channelName: "Composite: Loop ASMR", contentStyle: "Sound-first", estimatedEarnings: 3900, monthlyViews: 5_000_000, subscribersCount: 600_000, keySuccessFactors: ["Upload length", "Title SEO"], toolsUsed: ["Reaper"] },
    ],
  },
  {
    slug: "viral-memes-explained-faceless",
    nicheName: "Viral Memes Explained & Trend Breakdowns",
    categoryName: "Niche Hobbies",
    description:
      "Fast edits, context panels, and humor narration—ride trends without showing your face.",
    profitabilityScore: 7,
    difficultyLevel: "easy",
    competitionLevel: "high",
    estimatedEarningsRange: "$2K–$12K/mo",
    avgRpm: 6,
    startupCost: "$40–$200",
    timeToMonetization: "1–4 months",
    evergreenScore: 4,
    trendStatus: "rising",
    targetAudience: "Gen Z/millennial culture chasers.",
    primaryContentFocus: "Origin stories, format templates, weekly trend recap.",
    monetizationStrategies: ["Shorts funds", "Sponsorships", "Merch", "Patreon bonus cuts"],
    risks: ["Copyright—transformative commentary", "Brand safety"],
    requiredTools: ["Fast editor", "Meme asset workflow", "Caption presets"],
    bestAiTools: ["Trend scanning—human judgment"],
    longFormContent: `Meme explainers monetize through **speed and voice**. Publish while a trend peaks; compile evergreen “formats libraries” monthly.`,
    contentIdeas: [
      { contentTitle: "Why This Sound Took Over TikTok", contentFormat: "Shorts", seoPotential: "Low (trend)", estimatedProductionTime: "2–4 hrs", requiredTools: ["Clips"] },
      { contentTitle: "Meme Template Anatomy", contentFormat: "Explainer", seoPotential: "Medium", estimatedProductionTime: "5–8 hrs", requiredTools: ["Slides"] },
    ],
    caseStudies: [
      { channelName: "Composite: Culture Decoder", contentStyle: "Fast cuts + VO", estimatedEarnings: 5500, monthlyViews: 12_000_000, subscribersCount: 900_000, keySuccessFactors: ["Daily Shorts in spikes"], toolsUsed: ["CapCut"] },
    ],
  },
].map((n) => ({
  ...n,
  contentIdeas: n.contentIdeas.map((c, i) => ({ ...c, _id: id(`${n.slug}-idea-${i}`) })),
  caseStudies: n.caseStudies.map((c, i) => ({ ...c, _id: id(`${n.slug}-cs-${i}`) })),
})) as FallbackNicheFull[];
