import type { FallbackNicheFull, FallbackContentIdea, FallbackCaseStudy } from "./fallbackTypes";

type Seed = {
  slug: string;
  nicheName: string;
  categoryName: string;
  description: string;
  profitabilityScore: number;
  difficultyLevel: "easy" | "medium" | "hard";
  competitionLevel: "low" | "medium" | "high";
  avgRpm: number;
  trendStatus: "rising" | "stable" | "declining";
  evergreenScore: number;
  estimatedEarningsRange: string;
  startupCost: string;
  timeToMonetization: string;
};

function ideasFor(slug: string, name: string): FallbackContentIdea[] {
  const base = name.split("(")[0].trim();
  return [
    {
      _id: `fallback-${slug}-i0`,
      contentTitle: `${base}: Beginner Mistakes to Avoid`,
      contentFormat: "Long-form / Shorts mix",
      seoPotential: "High",
      estimatedProductionTime: "6–12 hrs",
      requiredTools: ["Screen or motion template", "VO"],
    },
    {
      _id: `fallback-${slug}-i1`,
      contentTitle: `Weekly ${base} Checklist (Steal This)`,
      contentFormat: "Carousel / Shorts",
      seoPotential: "Medium",
      estimatedProductionTime: "3–6 hrs",
      requiredTools: ["Canva"],
    },
    {
      _id: `fallback-${slug}-i2`,
      contentTitle: `Tools I Actually Use for ${base}`,
      contentFormat: "Affiliate-friendly tutorial",
      seoPotential: "Medium",
      estimatedProductionTime: "4–8 hrs",
      requiredTools: ["Screen capture"],
    },
  ];
}

function caseFor(slug: string, label: string): FallbackCaseStudy[] {
  return [
    {
      _id: `fallback-${slug}-cs0`,
      channelName: `Composite: ${label}`,
      contentStyle: "Faceless educational",
      estimatedEarnings: 4000 + (label.length * 37) % 4000,
      monthlyViews: 400_000 + (label.length * 9999) % 800_000,
      subscribersCount: 80_000 + (label.length * 1234) % 120_000,
      keySuccessFactors: ["Consistent uploads", "Search-led titles", "Template thumbnails"],
      toolsUsed: ["CapCut", "Canva", "Script assistant"],
    },
  ];
}

function expand(seed: Seed): FallbackNicheFull {
  const label = seed.nicheName.slice(0, 32);
  const longFormContent = `**${seed.nicheName}** fits the faceless model when you prioritize visuals, screen capture, or stock storytelling over on-camera charisma. In 2026, advertisers still reward clear educational intent—especially when your audience searches for specific outcomes. Start with a ten-video experiment: one hero long-form, three Shorts, and a repeatable thumbnail system. Track watch time and outbound clicks before scaling production. This entry is part of ContentAnonymity’s expanded database; combine it with our profitability calculator and niche quiz to validate demand in your region. Sustainability comes from updating top performers quarterly and layering affiliates only after trust is established.`;

  return {
    ...seed,
    monetizationStrategies: [
      "Platform ad revenue (YouTube/TikTok/FB programs where eligible)",
      "Affiliate tools and consumables relevant to the topic",
      "Digital templates, checklists, or mini-courses",
      "Sponsored segments with clear #ad disclosure",
      "Email list → recurring sponsor or product drops",
    ],
    risks: [
      "Platform policy changes—keep backups of scripts and assets",
      "Topic sensitivity: avoid medical/financial guarantees; add disclaimers",
      "Competition: differentiate with sub-niche angles and proof-driven hooks",
    ],
    requiredTools: ["Video editor", "Royalty-free music", "Thumbnail designer (Canva/Figma)"],
    bestAiTools: ["Script drafting (edited)", "Auto-captions", "Thumbnail text variants"],
    targetAudience: "Faceless creators and operators seeking searchable, monetizable topics.",
    primaryContentFocus: `Educational clarity, repeatable formats, and ethical CTAs tailored to ${label}.`,
    longFormContent,
    contentIdeas: ideasFor(seed.slug, seed.nicheName),
    caseStudies: caseFor(seed.slug, label),
  };
}

/** 80 additional niches to reach 100+ total (composite, educational — not individual testimonials). */
const SEEDS: Seed[] = [
  { slug: "real-estate-beginner-guides", nicheName: "Real Estate Concepts for Beginners", categoryName: "Finance & Wealth", description: "Explain mortgages, closing costs, and inspections with graphics and VO.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 16, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$4K–$16K/mo", startupCost: "$80–$350", timeToMonetization: "4–8 months" },
  { slug: "tax-tips-self-employed", nicheName: "Tax Tips for Freelancers & Self-Employed", categoryName: "Finance & Wealth", description: "Quarterly estimates, deductions, and simple spreadsheets—faceless screen tutorials.", profitabilityScore: 9, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 19, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$5K–$20K/mo", startupCost: "$100–$500", timeToMonetization: "4–9 months" },
  { slug: "student-loan-strategies", nicheName: "Student Loan Repayment Strategies", categoryName: "Finance & Wealth", description: "Compare plans with neutral math animations.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 15, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$70–$300", timeToMonetization: "3–7 months" },
  { slug: "side-income-surveys-reality", nicheName: "Side Income: Surveys & Microtasks (Reality Check)", categoryName: "Finance & Wealth", description: "Honest earnings math with charts—no hype.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$40–$150", timeToMonetization: "2–4 months" },
  { slug: "fire-movement-explained", nicheName: "FIRE Movement Explained (Financial Independence)", categoryName: "Finance & Wealth", description: "Savings rate visuals and scenario modeling.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 17, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$4K–$15K/mo", startupCost: "$80–$350", timeToMonetization: "4–8 months" },
  { slug: "mental-health-hygiene-education", nicheName: "Mental Health Literacy (Non-Clinical)", categoryName: "Health & Wellness", description: "Coping skills, therapy types explained—disclaimers required.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 11, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$80–$400", timeToMonetization: "4–8 months" },
  { slug: "sleep-hygiene-science", nicheName: "Sleep Hygiene & Circadian Tips", categoryName: "Health & Wellness", description: "Evidence-leaning explainers with calm motion.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$13K/mo", startupCost: "$60–$280", timeToMonetization: "3–6 months" },
  { slug: "stretching-desk-workers", nicheName: "Stretching for Desk Workers", categoryName: "Health & Wellness", description: "Follow-along timers with silhouette graphics.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$50–$220", timeToMonetization: "2–5 months" },
  { slug: "gut-health-basics", nicheName: "Gut Health Basics (General Education)", categoryName: "Health & Wellness", description: "Fiber, hydration, sleep links—avoid disease claims.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$80–$350", timeToMonetization: "4–8 months" },
  { slug: "skincare-science-simple", nicheName: "Skincare Science Simplified", categoryName: "Health & Wellness", description: "Ingredient explainers with text overlays—no medical claims.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 13, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$4K–$14K/mo", startupCost: "$100–$400", timeToMonetization: "3–7 months" },
  { slug: "ai-tools-for-creators", nicheName: "AI Tools for Creators (Weekly Roundups)", categoryName: "Tech & Productivity", description: "Screen demos of new tools—fast-moving but high interest.", profitabilityScore: 9, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 16, trendStatus: "rising", evergreenScore: 5, estimatedEarningsRange: "$5K–$22K/mo", startupCost: "$80–$400", timeToMonetization: "2–6 months" },
  { slug: "cybersecurity-awareness-home", nicheName: "Cybersecurity Tips for Everyday Users", categoryName: "Tech & Productivity", description: "Passwords, 2FA, phishing recognition with simple graphics.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 15, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$4K–$16K/mo", startupCost: "$70–$320", timeToMonetization: "3–7 months" },
  { slug: "no-code-automation", nicheName: "No-Code Automation (Zapier/Make)", categoryName: "Tech & Productivity", description: "Workflow builds with screen capture.", profitabilityScore: 9, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 17, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$5K–$18K/mo", startupCost: "$80–$350", timeToMonetization: "3–6 months" },
  { slug: "keyboard-customization", nicheName: "Mechanical Keyboards & Desk Ergonomics", categoryName: "Tech & Productivity", description: "Hands-only typing tests and sound comparisons.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$150–$600", timeToMonetization: "3–6 months" },
  { slug: "smart-home-setup-guides", nicheName: "Smart Home Setup for Renters", categoryName: "Tech & Productivity", description: "Hubs, bulbs, privacy settings—faceless walkthroughs.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 13, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$3K–$14K/mo", startupCost: "$200–$700", timeToMonetization: "4–8 months" },
  { slug: "photo-editing-lightroom-mobile", nicheName: "Mobile Photo Editing (Lightroom/VN)", categoryName: "Tech & Productivity", description: "Slider tutorials and preset sales.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$60–$250", timeToMonetization: "2–5 months" },
  { slug: "minimalism-declutter", nicheName: "Minimalism & Decluttering Systems", categoryName: "Lifestyle & Entertainment", description: "Before/after stock narratives and room layouts.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "cooking-one-pan-meals", nicheName: "One-Pan Meals & Batch Cooking", categoryName: "Lifestyle & Entertainment", description: "Overhead recipe content without showing identity.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$120–$450", timeToMonetization: "3–6 months" },
  { slug: "film-explained-simply", nicheName: "Movies Explained (Plot & Themes)", categoryName: "Lifestyle & Entertainment", description: "Analysis with stills under fair-use commentary.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$14K/mo", startupCost: "$80–$400", timeToMonetization: "4–9 months" },
  { slug: "true-crime-storytelling-faceless", nicheName: "True Crime Storytelling (Voice + Stock)", categoryName: "Lifestyle & Entertainment", description: "Respectful, source-cited narratives—avoid sensationalism.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$4K–$16K/mo", startupCost: "$100–$500", timeToMonetization: "4–10 months" },
  { slug: "productivity-for-students", nicheName: "Productivity Systems for Students", categoryName: "Business & Marketing", description: "Pomodoro, note-taking, exam timetables.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 12, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$50–$200", timeToMonetization: "2–5 months" },
  { slug: "linkedin-growth-faceless", nicheName: "LinkedIn Growth Without Showing Your Face", categoryName: "Business & Marketing", description: "Document posts and carousel frameworks.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 14, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$4K–$15K/mo", startupCost: "$60–$280", timeToMonetization: "3–7 months" },
  { slug: "ecommerce-seo-basics", nicheName: "E-commerce SEO Basics (Shopify/Woo)", categoryName: "Business & Marketing", description: "Technical explainers with screen capture.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 15, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$4K–$17K/mo", startupCost: "$80–$400", timeToMonetization: "4–9 months" },
  { slug: "print-on-demand-tips", nicheName: "Print-on-Demand Tips & Mockups", categoryName: "Business & Marketing", description: "Design workflows and marketplace comparisons.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 11, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$80–$350", timeToMonetization: "3–7 months" },
  { slug: "virtual-assistant-training", nicheName: "Virtual Assistant Skills (Beginner)", categoryName: "Business & Marketing", description: "Inbox systems, calendar etiquette, SOPs.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 13, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$13K/mo", startupCost: "$60–$280", timeToMonetization: "3–6 months" },
  { slug: "public-speaking-anxiety-tips", nicheName: "Public Speaking Anxiety (Non-Therapy Tips)", categoryName: "Evergreen Education", description: "Breathing drills and prep checklists—disclaimers.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$50–$220", timeToMonetization: "3–6 months" },
  { slug: "study-techniques-evidence", nicheName: "Study Techniques (Evidence-Lean)", categoryName: "Evergreen Education", description: "Active recall, spaced repetition explainers.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$50–$200", timeToMonetization: "3–6 months" },
  { slug: "history-explained-simple", nicheName: "History Explained (Animated Timelines)", categoryName: "Evergreen Education", description: "Wars, civilizations, maps—faceless narration.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 10, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$4K–$16K/mo", startupCost: "$100–$500", timeToMonetization: "5–12 months" },
  { slug: "science-experiments-at-home", nicheName: "Safe At-Home Science Demos", categoryName: "Evergreen Education", description: "Simple physics/chemistry with safety callouts.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$80–$400", timeToMonetization: "3–7 months" },
  { slug: "philosophy-for-life-decisions", nicheName: "Philosophy for Everyday Decisions", categoryName: "Evergreen Education", description: "Stoicism, ethics basics with quote animations.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "dog-training-basics", nicheName: "Dog Training Basics (Positive Reinforcement)", categoryName: "Niche Hobbies", description: "Techniques with stock dog footage—ethical framing.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$80–$350", timeToMonetization: "3–7 months" },
  { slug: "indoor-plants-care", nicheName: "Indoor Plants & Low-Light Care", categoryName: "Niche Hobbies", description: "Plant profiles with icon overlays.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 8, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$60–$250", timeToMonetization: "2–5 months" },
  { slug: "fishing-tips-beginners", nicheName: "Fishing Tips for Beginners", categoryName: "Niche Hobbies", description: "Knots, rigs, and gear explainers with diagrams.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$7K/mo", startupCost: "$100–$400", timeToMonetization: "3–7 months" },
  { slug: "board-games-explained", nicheName: "Board Game Rules Explained Fast", categoryName: "Niche Hobbies", description: "Top-down table stock + rule summaries.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "low", avgRpm: 7, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$60–$280", timeToMonetization: "3–6 months" },
  { slug: "watch-collecting-101", nicheName: "Watch Collecting 101 (Entry Level)", categoryName: "Niche Hobbies", description: "Movements, straps, care—hands-only optional.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$150–$600", timeToMonetization: "4–8 months" },
  { slug: "car-maintenance-basics", nicheName: "Car Maintenance Basics (DIY)", categoryName: "Niche Hobbies", description: "Oil, tires, fluids with safety emphasis.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 12, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$150–$600", timeToMonetization: "4–9 months" },
  { slug: "crypto-literacy-non-hype", nicheName: "Crypto Literacy (Non-Hype Education)", categoryName: "Finance & Wealth", description: "Wallets, keys, risks—avoid price promises.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 14, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$3K–$14K/mo", startupCost: "$80–$400", timeToMonetization: "4–10 months" },
  { slug: "insurance-explained-simple", nicheName: "Insurance Types Explained Simply", categoryName: "Finance & Wealth", description: "Term life, renters, umbrella—educational only.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 16, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$4K–$15K/mo", startupCost: "$80–$400", timeToMonetization: "5–10 months" },
  { slug: "resume-ats-optimization", nicheName: "Resume ATS Optimization", categoryName: "Business & Marketing", description: "Template teardowns and keyword hygiene.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 13, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "interview-answers-star", nicheName: "Interview Answers (STAR Method)", categoryName: "Business & Marketing", description: "Role-play audio + slide examples.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 12, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$10K/mo", startupCost: "$40–$160", timeToMonetization: "2–5 months" },
  { slug: "notion-second-brain", nicheName: "Notion Second Brain Templates", categoryName: "Tech & Productivity", description: "PARA, dashboards, capture flows—screen-led.", profitabilityScore: 9, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 15, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$5K–$18K/mo", startupCost: "$60–$280", timeToMonetization: "2–6 months" },
  { slug: "obsidian-pkm", nicheName: "Obsidian PKM for Beginners", categoryName: "Tech & Productivity", description: "Linking notes, plugins—developer-adjacent audience.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 14, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$4K–$14K/mo", startupCost: "$60–$260", timeToMonetization: "3–7 months" },
  { slug: "excel-for-finance-jobs", nicheName: "Excel for Financial Analyst Roles", categoryName: "Tech & Productivity", description: "Modeling hygiene with anonymized sheets.", profitabilityScore: 9, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 17, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$5K–$19K/mo", startupCost: "$80–$350", timeToMonetization: "4–9 months" },
  { slug: "powerpoint-storytelling", nicheName: "PowerPoint Storytelling for Work", categoryName: "Business & Marketing", description: "Slide makeovers and narrative arcs.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 11, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "remote-work-ergonomics", nicheName: "Remote Work Ergonomics & Setup", categoryName: "Health & Wellness", description: "Chair height, monitors, breaks—office-worker focus.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$80–$320", timeToMonetization: "3–6 months" },
  { slug: "hydration-electrolytes-basics", nicheName: "Hydration & Electrolytes (General)", categoryName: "Health & Wellness", description: "Sports vs daily needs—non-medical framing.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$7K/mo", startupCost: "$50–$200", timeToMonetization: "3–6 months" },
  { slug: "parenting-routines-toddlers", nicheName: "Parenting Routines for Toddlers", categoryName: "Lifestyle & Entertainment", description: "Schedules, boundaries—non-expert community tone.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$60–$250", timeToMonetization: "3–7 months" },
  { slug: "wedding-budget-hacks", nicheName: "Wedding Planning on a Budget", categoryName: "Lifestyle & Entertainment", description: "Spreadsheet culture + vendor tips—faceless slides.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$60–$260", timeToMonetization: "3–7 months" },
  { slug: "rv-travel-boondocking", nicheName: "RV Travel & Boondocking Basics", categoryName: "Lifestyle & Entertainment", description: "Power, water, safety explainers with stock RV footage.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$100–$400", timeToMonetization: "4–8 months" },
  { slug: "coffee-brewing-guides", nicheName: "Coffee Brewing Guides (Pour Over/Espresso)", categoryName: "Niche Hobbies", description: "Overhead shots, ratio graphics, gear affiliates.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$120–$450", timeToMonetization: "3–6 months" },
  { slug: "knitting-basics-animations", nicheName: "Knitting & Crochet Basics (Animations)", categoryName: "Niche Hobbies", description: "Stitch diagrams and slow tutorials.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$80–$300", timeToMonetization: "3–7 months" },
  { slug: "3d-printing-for-beginners", nicheName: "3D Printing for Beginners", categoryName: "Tech & Productivity", description: "Slicer settings, bed leveling, safety.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$300–$1200", timeToMonetization: "4–9 months" },
  { slug: "drone-cinematography-tips", nicheName: "Drone Cinematography Tips (Legal & Safe)", categoryName: "Tech & Productivity", description: "Rules, ND filters, shot lists—compliance first.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$800–$3000+", timeToMonetization: "5–12 months" },
  { slug: "voiceover-business-freelance", nicheName: "Voiceover Business for Freelancers", categoryName: "Business & Marketing", description: "Rates, demos, home booth—audio-first faceless.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$200–$800", timeToMonetization: "3–8 months" },
  { slug: "ugc-creator-training", nicheName: "UGC Creator Training for Brands", categoryName: "Business & Marketing", description: "Hooks, hooks, deliverables—hands-only demos.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "rising", evergreenScore: 6, estimatedEarningsRange: "$3K–$13K/mo", startupCost: "$100–$450", timeToMonetization: "3–7 months" },
  { slug: "notion-habit-trackers", nicheName: "Notion Habit Trackers & Streak Systems", categoryName: "Tech & Productivity", description: "Template sales + tutorials.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 13, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$50–$200", timeToMonetization: "2–5 months" },
  { slug: "chrome-extensions-dev", nicheName: "Chrome Extension Ideas for Productivity", categoryName: "Tech & Productivity", description: "Lightweight coding + UX tips.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 14, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$4K–$15K/mo", startupCost: "$80–$400", timeToMonetization: "4–10 months" },
  { slug: "saas-metrics-explained", nicheName: "SaaS Metrics Explained (MRR, Churn, CAC)", categoryName: "Business & Marketing", description: "Whiteboard animations for founders.", profitabilityScore: 9, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 17, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$5K–$20K/mo", startupCost: "$80–$400", timeToMonetization: "5–12 months" },
  { slug: "grant-writing-basics", nicheName: "Grant Writing Basics for Nonprofits", categoryName: "Evergreen Education", description: "Outlines, budgets, storytelling—slides + VO.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "low", avgRpm: 11, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$10K/mo", startupCost: "$60–$280", timeToMonetization: "4–10 months" },
  { slug: "college-essay-structures", nicheName: "College Essay Structures & Prompts", categoryName: "Evergreen Education", description: "Outline frameworks—avoid writing essays for students.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "sat-math-strategies", nicheName: "SAT Math Strategies (Conceptual)", categoryName: "Evergreen Education", description: "Problem types and pacing—educational fair use.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 12, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$60–$260", timeToMonetization: "4–9 months" },
  { slug: "physics-concepts-visualized", nicheName: "Physics Concepts Visualized", categoryName: "Evergreen Education", description: "Forces, energy, waves with animations.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$4K–$15K/mo", startupCost: "$100–$500", timeToMonetization: "5–12 months" },
  { slug: "chemistry-lab-theory", nicheName: "Chemistry Concepts (Lab-Free)", categoryName: "Evergreen Education", description: "Stoichiometry basics with diagrams.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$13K/mo", startupCost: "$80–$400", timeToMonetization: "5–12 months" },
  { slug: "geography-explained-maps", nicheName: "Geography Explained (Maps & Trade Winds)", categoryName: "Evergreen Education", description: "Map animations and regional profiles.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$80–$380", timeToMonetization: "4–10 months" },
  { slug: "music-theory-for-producers", nicheName: "Music Theory for Bedroom Producers", categoryName: "Niche Hobbies", description: "Scales, chords, rhythm—DAW screen + MIDI.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$120–$500", timeToMonetization: "3–8 months" },
  { slug: "synth-sound-design-basics", nicheName: "Synth Sound Design Basics", categoryName: "Niche Hobbies", description: "ADSR, filters, presets—faceless DAW capture.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$150–$600", timeToMonetization: "4–9 months" },
  { slug: "aquarium-setup-freshwater", nicheName: "Freshwater Aquarium Setup", categoryName: "Niche Hobbies", description: "Cycle explainers, stocking rules, maintenance.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$150–$600", timeToMonetization: "4–9 months" },
  { slug: "bonsai-care-basics", nicheName: "Bonsai Care Basics", categoryName: "Niche Hobbies", description: "Pruning concepts with stock closeups.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "low", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$100–$400", timeToMonetization: "4–9 months" },
  { slug: "camping-gear-lists", nicheName: "Camping Gear Lists by Climate", categoryName: "Lifestyle & Entertainment", description: "Checklists and layering systems.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$80–$350", timeToMonetization: "3–6 months" },
  { slug: "hiking-safety-navigation", nicheName: "Hiking Safety & Navigation Basics", categoryName: "Lifestyle & Entertainment", description: "Maps, compass apps, first aid kits.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$80–$350", timeToMonetization: "3–7 months" },
  { slug: "budget-wedding-photo-checklist", nicheName: "Budget Wedding Photo Shot Lists", categoryName: "Lifestyle & Entertainment", description: "Pose ideas with stock couples—respectful tone.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 8, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "home-office-lighting", nicheName: "Home Office Lighting for Video Calls", categoryName: "Tech & Productivity", description: "Cheap setups, color temp, glare control.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$120–$450", timeToMonetization: "2–5 months" },
  { slug: "streaming-setup-budget", nicheName: "Streaming Setup on a Budget", categoryName: "Tech & Productivity", description: "OBS basics, audio chain, overlays.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$200–$800", timeToMonetization: "3–7 months" },
  { slug: "podcast-editing-basics", nicheName: "Podcast Editing Basics (Audacity/Reaper)", categoryName: "Tech & Productivity", description: "Noise reduction, loudness, music ducking.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$80–$350", timeToMonetization: "3–7 months" },
  { slug: "voice-dubbing-anime-fandom", nicheName: "Voice Acting Tips (Fandom & Indie)", categoryName: "Niche Hobbies", description: "Mic technique, character prep—creative community.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$1K–$7K/mo", startupCost: "$150–$600", timeToMonetization: "3–8 months" },
  { slug: "comic-book-storytelling", nicheName: "Comic Storytelling & Panel Flow", categoryName: "Niche Hobbies", description: "Layout tutorials with stock art references.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "low", avgRpm: 7, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$60–$280", timeToMonetization: "3–8 months" },
  { slug: "nft-literacy-non-hype", nicheName: "NFT & Digital Ownership Literacy", categoryName: "Finance & Wealth", description: "Wallets, royalties, risks—non-investment tone.", profitabilityScore: 6, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 10, trendStatus: "declining", evergreenScore: 4, estimatedEarningsRange: "$1K–$8K/mo", startupCost: "$80–$400", timeToMonetization: "4–12 months" },
  { slug: "sustainable-living-tips", nicheName: "Sustainable Living Tips (Practical)", categoryName: "Lifestyle & Entertainment", description: "Reduce waste, energy habits—non-preachy.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 9, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "minimalist-wardrobe-capsule", nicheName: "Capsule Wardrobe Planning", categoryName: "Lifestyle & Entertainment", description: "Color palettes, outfit grids—stock fashion.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$60–$250", timeToMonetization: "2–5 months" },
  { slug: "study-abroad-planning", nicheName: "Study Abroad Planning Checklists", categoryName: "Evergreen Education", description: "Visa overview + school search tips—non-legal.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$60–$260", timeToMonetization: "3–7 months" },
  { slug: "scholarship-search-strategies", nicheName: "Scholarship Search Strategies", categoryName: "Evergreen Education", description: "Essay reuse, deadlines, organization systems.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$160", timeToMonetization: "2–5 months" },
  { slug: "english-grammar-for-work", nicheName: "English Grammar for Professional Writing", categoryName: "Evergreen Education", description: "Common mistakes with slide examples.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 11, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "sign-language-basics-intro", nicheName: "Sign Language Basics (Introductory)", categoryName: "Evergreen Education", description: "Respectful, cite local Deaf resources—avoid appropriation.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$80–$350", timeToMonetization: "4–10 months" },
  { slug: "data-privacy-for-families", nicheName: "Data Privacy for Families", categoryName: "Tech & Productivity", description: "Parental controls, account hygiene—neutral tone.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 13, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$60–$280", timeToMonetization: "3–7 months" },
  { slug: "chromebook-tips-students", nicheName: "Chromebook Tips for Students", categoryName: "Tech & Productivity", description: "Extensions, offline, storage—simple screen demos.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$180", timeToMonetization: "2–5 months" },
  { slug: "ipad-note-taking", nicheName: "iPad Note-Taking Workflows", categoryName: "Tech & Productivity", description: "GoodNotes vs Notability style comparisons.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 12, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$400–$1200", timeToMonetization: "2–6 months" },
  { slug: "android-customization", nicheName: "Android Customization (Launchers/KWGT)", categoryName: "Tech & Productivity", description: "Homescreen aesthetics + tutorials.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$80–$350", timeToMonetization: "2–6 months" },
  { slug: "keyboard-shortcuts-mastery", nicheName: "Keyboard Shortcuts Mastery (Win/Mac)", categoryName: "Tech & Productivity", description: "Speedrun productivity with on-screen keys.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 10, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$160", timeToMonetization: "2–5 months" },
  { slug: "freelance-writing-rates", nicheName: "Freelance Writing Rates & Pitches", categoryName: "Business & Marketing", description: "Email templates and rate calculators.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 13, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$40–$200", timeToMonetization: "3–7 months" },
  { slug: "social-media-analytics-basics", nicheName: "Social Media Analytics Basics", categoryName: "Business & Marketing", description: "CTR, saves, hooks—platform-agnostic education.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 13, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$60–$260", timeToMonetization: "3–7 months" },
  { slug: "customer-support-scripts", nicheName: "Customer Support Scripts & Empathy", categoryName: "Business & Marketing", description: "Role-play audio for SMB training.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "low", avgRpm: 11, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$180", timeToMonetization: "3–6 months" },
  { slug: "inventory-management-small-shop", nicheName: "Inventory Management for Small Shops", categoryName: "Business & Marketing", description: "Spreadsheet systems + barcode basics.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "low", avgRpm: 12, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$60–$280", timeToMonetization: "3–8 months" },
  { slug: "zettelkasten-method-simple", nicheName: "Zettelkasten Method (Simple Start)", categoryName: "Evergreen Education", description: "Note linking with paper or apps.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "speed-reading-myths", nicheName: "Speed Reading: Myths vs Reality", categoryName: "Evergreen Education", description: "Comprehension-first framing—evidence lean.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 8, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$40–$160", timeToMonetization: "3–6 months" },
  { slug: "memory-palace-basics", nicheName: "Memory Palace Basics for Students", categoryName: "Evergreen Education", description: "Step-by-step visualization drills.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$7K/mo", startupCost: "$40–$160", timeToMonetization: "3–6 months" },
  { slug: "journaling-prompts-mental-clarity", nicheName: "Journaling Prompts for Mental Clarity", categoryName: "Health & Wellness", description: "Non-clinical prompts with calm visuals.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 8, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$30–$120", timeToMonetization: "2–4 months" },
  { slug: "breathwork-basics-non-medical", nicheName: "Breathwork Basics (Non-Medical)", categoryName: "Health & Wellness", description: "Box breathing demos with disclaimers.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$50–$220", timeToMonetization: "3–6 months" },
  { slug: "posture-correction-desk", nicheName: "Posture Correction for Desk Jobs", categoryName: "Health & Wellness", description: "Exercise animations + ergonomic cues.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$50–$220", timeToMonetization: "2–5 months" },
  { slug: "meal-prep-vegetarian-budget", nicheName: "Vegetarian Meal Prep on a Budget", categoryName: "Health & Wellness", description: "Macro-friendly plant meals with overhead shots.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$100–$400", timeToMonetization: "3–6 months" },
  { slug: "intermittent-fasting-education", nicheName: "Intermittent Fasting (General Education)", categoryName: "Health & Wellness", description: "Windows, hydration—no medical promises.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 10, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$60–$260", timeToMonetization: "4–8 months" },
  { slug: "running-for-beginners-plans", nicheName: "Running Plans for Beginners", categoryName: "Health & Wellness", description: "Couch-to-5K style pacing with graphics.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$60–$250", timeToMonetization: "3–6 months" },
  { slug: "yoga-mobility-morning", nicheName: "Morning Mobility (Yoga-Inspired)", categoryName: "Health & Wellness", description: "Gentle flows with silhouette graphics.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$50–$220", timeToMonetization: "2–5 months" },
  { slug: "cooking-knife-skills", nicheName: "Knife Skills for Home Cooks", categoryName: "Lifestyle & Entertainment", description: "Overhead tutorials with safety emphasis.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 10, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$120–$450", timeToMonetization: "3–6 months" },
  { slug: "fermentation-basics-kitchen", nicheName: "Home Fermentation Basics", categoryName: "Lifestyle & Entertainment", description: "Safety-first kimchi/kraut explainers.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "low", avgRpm: 8, trendStatus: "rising", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$80–$320", timeToMonetization: "3–7 months" },
  { slug: "sourdough-starter-science", nicheName: "Sourdough Starter Science", categoryName: "Lifestyle & Entertainment", description: "Timelapse + troubleshooting charts.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 9, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$2K–$7K/mo", startupCost: "$80–$320", timeToMonetization: "3–7 months" },
  { slug: "houseplant-propagation", nicheName: "Houseplant Propagation Guides", categoryName: "Niche Hobbies", description: "Water vs soil with clear graphics.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$60–$250", timeToMonetization: "2–5 months" },
  { slug: "birdwatching-beginners", nicheName: "Birdwatching for Beginners", categoryName: "Niche Hobbies", description: "Binoculars, apps, ethics—outdoor B-roll.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "low", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$5K/mo", startupCost: "$120–$450", timeToMonetization: "3–7 months" },
  { slug: "chess-openings-basics", nicheName: "Chess Openings for Beginners", categoryName: "Niche Hobbies", description: "Board animations + practice prompts.", profitabilityScore: 7, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 8, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "rubiks-cube-beginners", nicheName: "Rubik’s Cube Beginner Method", categoryName: "Niche Hobbies", description: "Hands-only or digital cube sim.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$30–$120", timeToMonetization: "2–5 months" },
  { slug: "magic-tricks-card-basics", nicheName: "Card Magic Basics (Ethical Practice)", categoryName: "Niche Hobbies", description: "Angles, practice routines—hands visible.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$40–$180", timeToMonetization: "3–7 months" },
  { slug: "origami-tutorials-simple", nicheName: "Origami Tutorials (Simple Models)", categoryName: "Niche Hobbies", description: "Overhead paper folding with clear lighting.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 6, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$1K–$5K/mo", startupCost: "$40–$150", timeToMonetization: "2–5 months" },
  { slug: "calligraphy-basics-digital", nicheName: "Digital Calligraphy Basics", categoryName: "Niche Hobbies", description: "iPad lettering with brush presets.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$200–$800", timeToMonetization: "2–6 months" },
  { slug: "watercolor-textures-beginners", nicheName: "Watercolor Textures for Beginners", categoryName: "Niche Hobbies", description: "Overhead painting with supply links.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$80–$320", timeToMonetization: "2–5 months" },
  { slug: "bullet-journal-minimal", nicheName: "Minimal Bullet Journaling", categoryName: "Niche Hobbies", description: "Monthly setups without art pressure.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 7, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$40–$160", timeToMonetization: "2–5 months" },
  { slug: "stargazing-basics", nicheName: "Stargazing Basics (Northern Hemisphere)", categoryName: "Niche Hobbies", description: "Constellation apps, light pollution tips.", profitabilityScore: 6, difficultyLevel: "easy", competitionLevel: "low", avgRpm: 7, trendStatus: "stable", evergreenScore: 9, estimatedEarningsRange: "$1K–$5K/mo", startupCost: "$80–$350", timeToMonetization: "3–7 months" },
  { slug: "film-photography-basics", nicheName: "Film Photography Basics", categoryName: "Niche Hobbies", description: "Stock camera B-roll + scanning tips.", profitabilityScore: 6, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 8, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$1K–$6K/mo", startupCost: "$200–$900", timeToMonetization: "4–10 months" },
  { slug: "vintage-restoration-tips", nicheName: "Vintage Electronics Restoration (Safe)", categoryName: "Niche Hobbies", description: "Capacitors, safety—expert disclaimers.", profitabilityScore: 7, difficultyLevel: "hard", competitionLevel: "low", avgRpm: 9, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$2K–$8K/mo", startupCost: "$200–$800", timeToMonetization: "5–12 months" },
  { slug: "home-networking-wifi", nicheName: "Home Wi-Fi & Mesh Networking", categoryName: "Tech & Productivity", description: "Router placement, speed tests—screen-led.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 13, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$120–$500", timeToMonetization: "3–7 months" },
  { slug: "budget-pc-building", nicheName: "Budget PC Building Guides", categoryName: "Tech & Productivity", description: "Parts lists, compatibility, thermals.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "high", avgRpm: 12, trendStatus: "stable", evergreenScore: 7, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$200–$800", timeToMonetization: "3–8 months" },
  { slug: "used-car-inspection-checklist", nicheName: "Used Car Inspection Checklist", categoryName: "Niche Hobbies", description: "Under-hood B-roll + negotiation tips—non-legal.", profitabilityScore: 8, difficultyLevel: "medium", competitionLevel: "medium", avgRpm: 12, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$3K–$11K/mo", startupCost: "$150–$600", timeToMonetization: "4–9 months" },
  { slug: "home-buying-steps-overview", nicheName: "Home Buying Steps (High-Level)", categoryName: "Finance & Wealth", description: "Offer, inspection, closing—educational, not legal advice.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 15, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$4K–$14K/mo", startupCost: "$80–$400", timeToMonetization: "5–12 months" },
  { slug: "dividend-investing-basics", nicheName: "Dividend Investing Basics", categoryName: "Finance & Wealth", description: "Yield traps, payout ratios—neutral education.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 17, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$4K–$16K/mo", startupCost: "$100–$450", timeToMonetization: "5–12 months" },
  { slug: "options-basics-non-advice", nicheName: "Options Basics (Educational, Non-Advisory)", categoryName: "Finance & Wealth", description: "Calls/puts explained with risk warnings.", profitabilityScore: 8, difficultyLevel: "hard", competitionLevel: "high", avgRpm: 16, trendStatus: "stable", evergreenScore: 6, estimatedEarningsRange: "$3K–$14K/mo", startupCost: "$100–$500", timeToMonetization: "5–12 months" },
  { slug: "small-business-bookkeeping-intro", nicheName: "Small Business Bookkeeping Intro", categoryName: "Business & Marketing", description: "Chart of accounts, reconciliations—CPA disclaimers.", profitabilityScore: 9, difficultyLevel: "hard", competitionLevel: "medium", avgRpm: 16, trendStatus: "stable", evergreenScore: 8, estimatedEarningsRange: "$5K–$18K/mo", startupCost: "$80–$400", timeToMonetization: "5–12 months" },
  { slug: "content-repurposing-system", nicheName: "Content Repurposing Systems", categoryName: "Business & Marketing", description: "One pillar → Shorts, pins, newsletter—SOP led.", profitabilityScore: 8, difficultyLevel: "easy", competitionLevel: "high", avgRpm: 12, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$3K–$12K/mo", startupCost: "$50–$220", timeToMonetization: "2–6 months" },
  { slug: "faceless-channel-branding", nicheName: "Faceless Channel Branding & Visual Systems", categoryName: "Business & Marketing", description: "Fonts, colors, thumbnail grids—meta niche.", profitabilityScore: 7, difficultyLevel: "easy", competitionLevel: "medium", avgRpm: 11, trendStatus: "rising", evergreenScore: 8, estimatedEarningsRange: "$2K–$9K/mo", startupCost: "$40–$200", timeToMonetization: "2–5 months" },
];

export const FALLBACK_BULK_NICHES: FallbackNicheFull[] = SEEDS.map(expand);
